### ISSUE TITLE
Can I change CDN path after init?

### ISSUE THREAD

**Issue by khunshan** [Viblast/ios-player-sdk#1]
I am using this to alloc and init player

  `self.player = [[VBPlayer alloc]
                 initWithCDN:xxx
                 enabledPDN:NO
                 licenseKey:nil];`

However, can I just `init` and set CDN later like something
`[self.player setCDN:xxx]`

**Comment by ivermolaev** [comment]
Hi there,
The CDN is a constitutive part of the player so it must be provided in its initialization method. Having a mutator will mean that you'll be able to swap it while playing i.e., to stop and start the process of loading the playback again. For that purpose you can just reinitialize the player with the new CDN.
