### ISSUE TITLE
inTimeStamp assertion failure

### ISSUE THREAD

**Issue by mirjalolbahodirov** [Viblast/ios-player-sdk#9]
Hi
in Xcode 8 demo app crash (simulator iOS 10)
example mpd is **http://dash.edgesuite.net/envivio/EnvivioDash3/manifest.mpd**
Error screenshot is here:
<img width="1440" alt="screen shot 2016-11-12 at 12 28 16" src="https://cloud.githubusercontent.com/assets/12315407/20236361/e03f8ec4-a8d3-11e6-9abf-9a4890ff0842.png">

**Comment by ivermolaev** [comment]
Thank you @mirjalolbahodirov!
Sorry for the late reply I'm on it.

**Comment by ivermolaev** [comment]
Fixed

**Comment by mirjalolbahodirov** [comment]
Hi, @ivermolaev! Thank you for attention! Can I use this library without watermark for educational purposes. I need to create video tutorial app for my country. If it is possible, please, let me know, how?
